export const words = [
  'chair', 'table', 'book', 'pen', 'phone',
  'cup', 'plate', 'fork', 'spoon', 'knife',
  'shoe', 'shirt', 'pants', 'hat', 'bag',
  'car', 'bike', 'bus', 'train', 'plane',
  'door', 'window', 'bed', 'lamp', 'clock',
  'key', 'wallet', 'coin', 'paper', 'box',
  'bottle', 'glass', 'mirror', 'brush', 'towel',
  'soap', 'toothbrush', 'pillow', 'blanket', 'camera',
  'computer', 'television', 'radio', 'flower',
  'sun', 'moon', 'star', 'cloud', 'rain',
  'notebook', 'pencil', 'eraser', 'ruler', 'scissors',
  'stapler', 'tape', 'glue', 'folder', 'binder',
  'backpack', 'calculator', 'printer', 'mouse', 'keyboard',
  'monitor', 'speaker', 'microphone', 'headphones', 'charger',
  'tablet', 'smartwatch', 'remote', 'controller', 'joystick',
  'game', 'puzzle', 'toy', 'doll', 'ball',
  'bat', 'racket', 'net', 'goal', 'helmet',
  'gloves', 'goggles', 'mask', 'snorkel', 'flippers',
  'umbrella', 'raincoat', 'boots', 'scarf',
  'jacket', 'sweater', 'coat', 'dress', 'skirt',
  'shorts', 'blouse', 'tie',
  'suit', 'tuxedo', 'shoes', 'heels',
  'lemon', 'apple', 'banana', 'orange', 'grape',
  'strawberry', 'blueberry', 'raspberry', 'blackberry', 'cherry',
  'peach', 'pear', 'plum', 'kiwi', 'pineapple',
  'bread', 'butter', 'cheese', 'milk', 'yogurt',
  'egg', 'bacon', 'sausage', 'ham', 'steak',
  'chicken', 'turkey', 'duck', 'fish', 'shrimp',
  'crab', 'lobster', 'clam', 'oyster', 'mussel',
  'tree', 'grass', 'bush', 'weed',
  'rock', 'dirt', 'sand', 'water', 'river',
  'lake', 'ocean', 'wave', 'tide', 'current',
  'wind', 'breeze', 'gust', 'storm', 'hurricane',
  'tornado', 'earthquake', 'volcano', 'tsunami', 'flood',
  'fire', 'smoke', 'ash', 'lava', 'magma',
  'snow', 'hail', 'sleet',
  'fog', 'mist', 'dew', 'ice', 'frost'
];